[extend]
useDefault = true

[allowlist]
paths = [
  '''(^|/)node_modules(/|$)''',
  '''(^|/)\.git(/|$)''',
  '''(^|/)dist(/|$)''',
  '''(^|/)build(/|$)''',
  '''.*\.lock$''',
  '''.*fixtures?/.*'''
]
