apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: myshare-dev

resources:
  - namespace.yaml
  - pvc.yaml
  - deployment.yaml
  - hc.yaml
  - hr.yaml
  - networkpolicy.yaml
  - service.yaml
  - svc-hl.yaml
