name: Lint Text

on:
  push:
    branches:
      - dev
      - main
    paths:
      - '**/*.js'
      - '**/*.ts'
      - '**/*.vue'
      - '**/*.html'
      - '**/*.css'
      - '**/*.scss'
      - '**/*.less'
      - '**/*.json'
      - '**/*.jsonc'
      - '**/*.yaml'
      - '**/*.yml'
      - '**/*.toml'
      - '**/*.xml'
      - '**/*.md'
      - '**/*.mdc'
      - '**/*.mdс'
      - '**/*.txt'
      - '**/*.go'
      - '**/*.py'
      - '**/*.php'
      - '**/*.sh'

  pull_request:
    branches:
      - dev
      - main

concurrency:
  group: ${{ github.ref }}-${{ github.workflow }}
  cancel-in-progress: true

jobs:
  text:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v6
        with:
          persist-credentials: false

      - uses: ./.github/actions/setup-bun-deps

      - name: Install shellcheck
        run: sudo apt-get update && sudo apt-get install -y shellcheck

      - name: Install dotenv-linter
        run: >-
          curl -sSfL https://git.io/JLbXn
          | sh -s -- -b /usr/local/bin

      - name: Lint text
        run: bunx n-cursor lint text --no-fix
